services:
  ray-head:
    build:
      context: .
      dockerfile: Dockerfile
    image: mmseg-cuda121:ray
    container_name: ray-head
    runtime: nvidia
    shm_size: '16gb'
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - MLFLOW_TRACKING_URI=http://129.114.27.198:8000
      - AWS_ACCESS_KEY_ID=your-access-key
      - AWS_SECRET_ACCESS_KEY=your-secret-key
      - MLFLOW_S3_ENDPOINT_URL=http://129.114.27.198:9000
    volumes:
      - ./PlantSeg:/workspace/PlantSeg
      - /mnt/object:/workspace/PlantSeg/data/plantseg115
    ports:
      - "8888:8888"   # JupyterLab
      - "8265:8265"   # Ray Dashboard
      - "6379:6379"   # Ray head port
    working_dir: /workspace
    command: >
      bash -c "
      ray start --head --port=6379 --dashboard-host=0.0.0.0 --dashboard-port=8265 &&
      jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --notebook-dir=/workspace
      "

  ray-worker:
    image: mmseg-cuda121:ray
    container_name: ray-worker
    runtime: nvidia
    shm_size: '16gb'
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - MLFLOW_TRACKING_URI=http://129.114.27.198:8000
      - AWS_ACCESS_KEY_ID=your-access-key
      - AWS_SECRET_ACCESS_KEY=your-secret-key
      - MLFLOW_S3_ENDPOINT_URL=http://129.114.27.198:9000
    volumes:
      - ./PlantSeg:/workspace/PlantSeg
      - /mnt/object:/workspace/PlantSeg/data/plantseg115
    depends_on:
      - ray-head
    working_dir: /workspace
    command: >
      bash -c "
      ray start --address=ray-head:6379 --block
      "
